# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5e6cccb5c47b0c2b77514bde4ba28bf758553b5c47a49f43393bc5f11fc6d262d0bf74c0d89f9ed5687a954a3112088e42d4a94c23e09e588538f8ef971abb7

test:
  secret_key_base: 02ba6fd2f99ced7dc637bef7e7690605058d521ceda238e19745cc135b6800c802978407e84f8743865441eed52d140fbd8ffff8b7b842c508dfbd6f4d32fbce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
